repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.13.0
    hooks:
      - id: markdownlint
        args:
          - "-r ~MD013"
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.2
    hooks:
      - id: actionlint
  - repo: https://github.com/crate-ci/typos
    rev: v1.24.6
    hooks:
      - id: typos
        args: ["--config", ".github/linters/typos.toml"]
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.19.0"
    hooks:
      - id: terraform-docs-go
        args: ["-c", ".github/linters/.terraform-docs.yml", "."]

  # Terraform
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.98.0
    hooks:
      # ref: https://github.com/antonbabenko/pre-commit-terraform?tab=readme-ov-file#terraform_providers_lock
      - id: terraform_providers_lock
        name: "Generate lock-files for Terraform providers"
        files: .*\.tf$
        args:
          - --hook-config=--mode=only-check-is-current-lockfile-cross-platform
      - id: terraform_fmt
        name: "Format the Terraform configuration"
        files: .*\.tf$
        args:
          - --args=-diff
      # see reference option 4
      # ref: https://github.com/antonbabenko/pre-commit-terraform?tab=readme-ov-file#terraform_validate
      - id: terraform_validate
        exclude: 'examples/(full)/[^/]+$'
        name: "Validate the Terraform configuration"
        files: .*\.tf$
        args:
          - --hook-config=--retry-once-with-cleanup=true

  # Local hooks
  - repo: local
    hooks:
      - id: prettier_fmt
        name: "Format the Markdown files with Prettier"
        language: system
        files: .*\.md$
        entry: |
          bash -c 'prettier --write *.md'
