[default]
extend-ignore-identifiers-re = ["hel.*", "Hashi.*", "ANC.*"]

[default.extend-identifiers]
HashiCorp = "HashiCorp"
ANC = "ANC"

[default.extend-words]
hel = "hel"             # do not correct the 'hel' designation the Helsinki datacenter
HashiCorp = "HashiCorp" # do not correct HashiCorp
ANC = "ANC"
